Improve error handling in the `vault` script

diff --git a/files/scripts/vault b/files/scripts/vault
--- a/files/scripts/vault
+++ b/files/scripts/vault
@@ -3,52 +3,53 @@
 function check_exist() {
 	if [ -e $1 ]
 	then
-		read -p "'$1' already exists, remove? " -n 1 -r
-		echo
-		if [[ $REPLY =~ ^[Yy]$ ]]
-		then
-			rm $1
-		else
-			exit 1
-		fi
+		echo "File '$1' already exists"
+		prompt_remove $1 || return 1
 	fi
 }
 
-function prompt_deletion() {
-	read -p "Delete file: $1? " -n 1 -r
+function prompt_remove() {
+	read -p "Remove file: $1? " -n 1 -r
 	echo
 	if [[ $REPLY =~ ^[Yy]$ ]]
 	then
-		rm -rf $1
-		echo "File $1 deleted"
+		rm -rf $1 && echo "File $1 removed" && return 0
 	fi
+	return 1
 }
 
 function encrypt_dir() {
 	local enc_name="$(basename $1).enc"
-	check_exist $enc_name
+	check_exist $enc_name || return 1
 
-	echo "Compressing and encrypting $1 -> $enc_name..." && \
-		tar -cf - $1 | gpg --cipher-algo AES256 -co $enc_name && \
-		echo "Successfully encrypted: $enc_name" && \
-		prompt_deletion $1
+	echo "Creating and encrypting $1 -> $enc_name..."
+	(tar -cf - $1 | gpg --cipher-algo AES256 -co $enc_name) || (echo "Failed to create an encrypted file" && return 1)
+	echo "Successfully encrypted: $enc_name"
+	prompt_remove $1 || return 0 # file removal is optional
 }
 
 function decrypt_dir() {
 	local base=$(basename $1)
 	local dest="${base%.*}"
-	check_exist $dest
-	echo "Decrypting and decompressing $1 -> $dest..." && gpg -d $1 | tar -x
+	check_exist $dest || return 1
+	echo "Decrypting and extracting $1 -> $dest..."
+	(gpg -d $1 | tar -x) || (echo "Failed to decrypt $1" && return 1)
 }
 
-if [ -z ${1+x} ] || [ -z ${2+x} ]; then
-	echo "Usage: vault <enc|dec> <file>"
-	exit 1
-fi;
-
 case "$1" in
-	enc) encrypt_dir $2
-		 ;;
-	dec) decrypt_dir $2
-		 ;;
+	enc)
+		encrypt_dir $2 || exit 1
+		;;
+	dec)
+		decrypt_dir $2 || exit 1
+		;;
+	*)
+		echo "Usage: vault COMMAND FILE"
+		echo
+		echo "Encrypts/Decrypts a file/directory with AES256"
+		echo
+		echo "Commands:"
+		echo "enc — encrypt file"
+		echo "dec — decrypt file"
+		;;
 esac
